import random as rd
def game():
    a=rd.randrange(1,101)
    print('both will continue gussing one by one untill one player wins')
    for i in range(21):
     b=int(input("Enter Your Guess"))
     
     if(b==a):
        print("You Won!!!! Congrats")
        return 
     elif(b<a and i!=20):
        print("\n\nyou try a greater number to defeat your friend.")
     elif(b>a and i!=20):
        print("\n\nyou try a lesser number to win the game.")
    print("The correct number is:- ",a)

def main():
    if __name__ == '__main__':
        main()
        
 print('--------------------INSTRUCTIONS----------------------')
 print('1] It\'s a game of two palyers')
 print('2] this game is about guessing the number generated by system')
 print('3] both  will get maximum of 10 chances to guess')
 print('4] which player among you will guess it first will win\n\n')
 print('press 1 to start the game:\n')
 if(int(input())==1):
     print('lets do a toss to decide who will first guess')
     print('press 1 to toss')
     if(int(input())==1):
         a=rd.randrange(1,3)
         if(a==1):
             print('player 1 will start the game')
         if(a==2):
             print('player 2 will start the game') 
 game()  
 print("----------------GAME OVER----------------------")
 print('\n\nenter 1 to replay the game:\nenter 0 to exit the game')
 x=int(input()) 
 if(x==1):
     if __name__ == '__main__':
         main()
         
     

     
